version: '3.8'
services:
  api:
    command: >
      sh -c "
      npx prisma generate &&
      npx prisma migrate deploy &&
      npx prisma db push --accept-data-loss &&
      npx prisma studio --port 5555 --hostname 0.0.0.0 &
      npm run start:dev
      "
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/userdb?schema=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_BROKERS=kafka:29092
    ports:
      - "3000:3000"
      - "5555:5555" 