version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        - BUILDKIT_INLINE_CACHE=1
        - NPM_VERSION=11.3.0
      cache_from:
        - type=registry,ref=node:20-alpine
    container_name: ${DEPLOY_SHA:-${API_CONTAINER}}
    hostname: api
    ports:
      - "${API_PORT}:${API_PORT}"
      - "5555:5555"
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
      CORS_ORIGIN: "*"
      FRONTEND_URL: https://${FRONTEND_DOMAIN}
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD:-postgres}@postgres:${POSTGRES_PORT}/userdb?schema=public
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      TRUST_PROXY: 1
      PRISMA_SCHEMA_PATH: /app/src/shared/database/prisma/schema.prisma
      HOST: 0.0.0.0
      PORT: ${API_PORT}
      BIND_ADDRESS: 0.0.0.0
      SOCKET_HOST: 0.0.0.0
      SOCKET_PORT: ${API_PORT}
      SSL_KEY_PATH: ${APP_SSL_DIR}/${API_KEY}
      SSL_CERT_PATH: ${APP_SSL_DIR}/${API_CERT}
      NPM_CONFIG_LOGLEVEL: error
    expose:
      - "${API_PORT}"
      - "5555"
    networks:
      - app-network
    volumes:
      - ./logs:/app/logs
      - ./nginx/ssl:${APP_SSL_DIR}:ro
      - ./nginx/ssl:${SSL_DIR}:ro
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-check-certificate", "-q", "--spider", "https://localhost:${API_PORT}/${HEALTH_CHECK_ENDPOINT}"]
      interval: ${HEALTH_CHECK_INTERVAL}
      timeout: ${HEALTH_CHECK_TIMEOUT}
      retries: ${HEALTH_CHECK_RETRIES}
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

  postgres:
    image: postgres:latest
    container_name: ${DEPLOY_SHA:-${POSTGRES_CONTAINER}}
    hostname: postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: userdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/shared/database/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
    restart: unless-stopped
    shm_size: 128mb

  redis:
    image: redis:latest
    container_name: ${DEPLOY_SHA:-${REDIS_CONTAINER}}
    hostname: redis
    command: >
      redis-server 
      --appendonly yes 
      --maxmemory 512mb 
      --maxmemory-policy allkeys-lru 
      --save 900 1 
      --save 300 10 
      --save 60 10000
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    restart: unless-stopped
    sysctls:
      net.core.somaxconn: 1024
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: ${DEPLOY_SHA:-${REDIS_COMMANDER_CONTAINER}}
    hostname: redis-commander
    ports:
      - "${REDIS_COMMANDER_PORT}:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=${REDIS_COMMANDER_USER:-admin}
      - HTTP_PASSWORD=${REDIS_COMMANDER_PASSWORD:-admin}
      - TRUST_PROXY=true
      - HTTPS_ENABLED=true
    depends_on:
      - redis
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8081/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    name: ${NETWORK_NAME}
    driver: bridge 