/**
 * Centralized error codes for the healthcare application
 * Each error code follows the pattern: [MODULE]_[TYPE]_[SPECIFIC]
 *
 * @enum {string} ErrorCode
 * @description Comprehensive error code enumeration for healthcare application
 * @example
 * ```typescript
 * throw new HealthcareError(ErrorCode.USER_NOT_FOUND, 'User not found');
 * ```
 */
export enum ErrorCode {
  // Authentication & Authorization Errors
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_INSUFFICIENT_PERMISSIONS = 'AUTH_INSUFFICIENT_PERMISSIONS',
  AUTH_ACCOUNT_LOCKED = 'AUTH_ACCOUNT_LOCKED',
  AUTH_ACCOUNT_DISABLED = 'AUTH_ACCOUNT_DISABLED',
  AUTH_OTP_INVALID = 'AUTH_OTP_INVALID',
  AUTH_OTP_EXPIRED = 'AUTH_OTP_EXPIRED',
  AUTH_SESSION_EXPIRED = 'AUTH_SESSION_EXPIRED',

  // User Management Errors
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_EMAIL_ALREADY_EXISTS = 'USER_EMAIL_ALREADY_EXISTS',
  USER_PHONE_ALREADY_EXISTS = 'USER_PHONE_ALREADY_EXISTS',
  USER_PROFILE_INCOMPLETE = 'USER_PROFILE_INCOMPLETE',
  USER_ROLE_INVALID = 'USER_ROLE_INVALID',

  // Clinic Management Errors
  CLINIC_NOT_FOUND = 'CLINIC_NOT_FOUND',
  CLINIC_ALREADY_EXISTS = 'CLINIC_ALREADY_EXISTS',
  CLINIC_ACCESS_DENIED = 'CLINIC_ACCESS_DENIED',
  CLINIC_LICENSE_EXPIRED = 'CLINIC_LICENSE_EXPIRED',
  CLINIC_QUOTA_EXCEEDED = 'CLINIC_QUOTA_EXCEEDED',
  CLINIC_ID_REQUIRED = 'CLINIC_ID_REQUIRED',

  // IPD / Bed Management Errors
  IPD_BED_NOT_FOUND = 'IPD_BED_NOT_FOUND',
  IPD_BED_NOT_AVAILABLE = 'IPD_BED_NOT_AVAILABLE',
  IPD_PATIENT_ALREADY_ADMITTED = 'IPD_PATIENT_ALREADY_ADMITTED',
  IPD_TRANSFER_INVALID_STATUS = 'IPD_TRANSFER_INVALID_STATUS',
  IPD_TARGET_BED_NOT_FOUND = 'IPD_TARGET_BED_NOT_FOUND',
  IPD_BED_WARD_MISMATCH = 'IPD_BED_WARD_MISMATCH',
  IPD_TARGET_BED_NOT_AVAILABLE = 'IPD_TARGET_BED_NOT_AVAILABLE',
  IPD_ALREADY_DISCHARGED = 'IPD_ALREADY_DISCHARGED',
  IPD_WARD_ALREADY_EXISTS = 'IPD_WARD_ALREADY_EXISTS',
  IPD_WARD_NOT_FOUND = 'IPD_WARD_NOT_FOUND',
  IPD_BED_ALREADY_EXISTS = 'IPD_BED_ALREADY_EXISTS',
  IPD_ADMISSION_NOT_FOUND = 'IPD_ADMISSION_NOT_FOUND',
  IPD_BED_OCCUPIED_TRANSFER_REQUIRED = 'IPD_BED_OCCUPIED_TRANSFER_REQUIRED',

  // Appointment Errors
  APPOINTMENT_NOT_FOUND = 'APPOINTMENT_NOT_FOUND',
  APPOINTMENT_ALREADY_EXISTS = 'APPOINTMENT_ALREADY_EXISTS',
  APPOINTMENT_CONFLICT = 'APPOINTMENT_CONFLICT',
  APPOINTMENT_CANNOT_CANCEL = 'APPOINTMENT_CANNOT_CANCEL',
  APPOINTMENT_CANNOT_RESCHEDULE = 'APPOINTMENT_CANNOT_RESCHEDULE',
  APPOINTMENT_SLOT_UNAVAILABLE = 'APPOINTMENT_SLOT_UNAVAILABLE',
  APPOINTMENT_PAST_DATE = 'APPOINTMENT_PAST_DATE',

  // Check-In Errors
  CHECKIN_NO_APPOINTMENT_FOUND = 'CHECKIN_NO_APPOINTMENT_FOUND',
  CHECKIN_ALREADY_CONFIRMED = 'CHECKIN_ALREADY_CONFIRMED',
  CHECKIN_WRONG_LOCATION = 'CHECKIN_WRONG_LOCATION',
  CHECKIN_APPOINTMENT_EXPIRED = 'CHECKIN_APPOINTMENT_EXPIRED',
  CHECKIN_TIME_WINDOW_EXPIRED = 'CHECKIN_TIME_WINDOW_EXPIRED',
  CHECKIN_INVALID_QR_CODE = 'CHECKIN_INVALID_QR_CODE',

  // Doctor & Staff Errors
  DOCTOR_NOT_FOUND = 'DOCTOR_NOT_FOUND',
  DOCTOR_UNAVAILABLE = 'DOCTOR_UNAVAILABLE',
  DOCTOR_ALREADY_ASSIGNED = 'DOCTOR_ALREADY_ASSIGNED',
  STAFF_NOT_FOUND = 'STAFF_NOT_FOUND',
  STAFF_UNAUTHORIZED = 'STAFF_UNAUTHORIZED',

  // Patient Errors
  PATIENT_NOT_FOUND = 'PATIENT_NOT_FOUND',
  PATIENT_ALREADY_EXISTS = 'PATIENT_ALREADY_EXISTS',
  PATIENT_RECORD_LOCKED = 'PATIENT_RECORD_LOCKED',
  PATIENT_CONSENT_REQUIRED = 'PATIENT_CONSENT_REQUIRED',

  // Validation Errors
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  VALIDATION_REQUIRED_FIELD = 'VALIDATION_REQUIRED_FIELD',
  VALIDATION_INVALID_FORMAT = 'VALIDATION_INVALID_FORMAT',
  VALIDATION_INVALID_EMAIL = 'VALIDATION_INVALID_EMAIL',
  VALIDATION_INVALID_PHONE = 'VALIDATION_INVALID_PHONE',
  VALIDATION_INVALID_DATE = 'VALIDATION_INVALID_DATE',
  VALIDATION_INVALID_TIME = 'VALIDATION_INVALID_TIME',
  VALIDATION_INVALID_UUID = 'VALIDATION_INVALID_UUID',
  VALIDATION_STRING_TOO_LONG = 'VALIDATION_STRING_TOO_LONG',
  VALIDATION_STRING_TOO_SHORT = 'VALIDATION_STRING_TOO_SHORT',
  VALIDATION_NUMBER_OUT_OF_RANGE = 'VALIDATION_NUMBER_OUT_OF_RANGE',

  // Database Errors
  DATABASE_CONNECTION_FAILED = 'DATABASE_CONNECTION_FAILED',
  DATABASE_QUERY_FAILED = 'DATABASE_QUERY_FAILED',
  DATABASE_QUERY_TIMEOUT = 'DATABASE_QUERY_TIMEOUT',
  DATABASE_TRANSACTION_FAILED = 'DATABASE_TRANSACTION_FAILED',
  DATABASE_CONSTRAINT_VIOLATION = 'DATABASE_CONSTRAINT_VIOLATION',
  DATABASE_RECORD_NOT_FOUND = 'DATABASE_RECORD_NOT_FOUND',
  DATABASE_DUPLICATE_ENTRY = 'DATABASE_DUPLICATE_ENTRY',

  // External Service Errors
  EXTERNAL_SERVICE_UNAVAILABLE = 'EXTERNAL_SERVICE_UNAVAILABLE',
  EXTERNAL_SERVICE_TIMEOUT = 'EXTERNAL_SERVICE_TIMEOUT',
  EXTERNAL_SERVICE_INVALID_RESPONSE = 'EXTERNAL_SERVICE_INVALID_RESPONSE',
  EMAIL_SERVICE_FAILED = 'EMAIL_SERVICE_FAILED',
  SMS_SERVICE_FAILED = 'SMS_SERVICE_FAILED',
  WHATSAPP_SERVICE_FAILED = 'WHATSAPP_SERVICE_FAILED',
  PAYMENT_SERVICE_FAILED = 'PAYMENT_SERVICE_FAILED',

  // Cache Errors
  CACHE_CONNECTION_FAILED = 'CACHE_CONNECTION_FAILED',
  CACHE_OPERATION_FAILED = 'CACHE_OPERATION_FAILED',
  CACHE_KEY_NOT_FOUND = 'CACHE_KEY_NOT_FOUND',
  CACHE_INVALIDATION_FAILED = 'CACHE_INVALIDATION_FAILED',
  CACHE_CONFIGURATION_ERROR = 'CACHE_CONFIGURATION_ERROR',
  CACHE_TIMEOUT = 'CACHE_TIMEOUT',
  CACHE_SERIALIZATION_ERROR = 'CACHE_SERIALIZATION_ERROR',

  // Event Errors
  EVENT_EMISSION_FAILED = 'EVENT_EMISSION_FAILED',
  EVENT_PROCESSING_FAILED = 'EVENT_PROCESSING_FAILED',
  EVENT_SUBSCRIPTION_FAILED = 'EVENT_SUBSCRIPTION_FAILED',

  // Queue Errors
  QUEUE_INITIALIZATION_FAILED = 'QUEUE_INITIALIZATION_FAILED',
  QUEUE_OPERATION_FAILED = 'QUEUE_OPERATION_FAILED',
  QUEUE_JOB_NOT_FOUND = 'QUEUE_JOB_NOT_FOUND',
  QUEUE_NOT_FOUND = 'QUEUE_NOT_FOUND',
  QUEUE_AT_CAPACITY = 'QUEUE_AT_CAPACITY',
  QUEUE_PATIENT_ALREADY_QUEUED = 'QUEUE_PATIENT_ALREADY_QUEUED',
  QUEUE_INVALID_TRANSITION = 'QUEUE_INVALID_TRANSITION',
  QUEUE_NO_WAITING_PATIENTS = 'QUEUE_NO_WAITING_PATIENTS',
  EVENT_QUERY_FAILED = 'EVENT_QUERY_FAILED',
  EVENT_CIRCUIT_BREAKER_OPEN = 'EVENT_CIRCUIT_BREAKER_OPEN',

  // Logging Errors
  LOGGING_INITIALIZATION_FAILED = 'LOGGING_INITIALIZATION_FAILED',
  LOGGING_OPERATION_FAILED = 'LOGGING_OPERATION_FAILED',
  LOGGING_RETRIEVAL_FAILED = 'LOGGING_RETRIEVAL_FAILED',
  LOGGING_CLEAR_FAILED = 'LOGGING_CLEAR_FAILED',

  // File & Media Errors
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  FILE_INVALID_FORMAT = 'FILE_INVALID_FORMAT',
  FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED',
  FILE_DOWNLOAD_FAILED = 'FILE_DOWNLOAD_FAILED',
  FILE_DELETE_FAILED = 'FILE_DELETE_FAILED',

  // Rate Limiting & Security
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  SECURITY_VIOLATION = 'SECURITY_VIOLATION',
  SUSPICIOUS_ACTIVITY = 'SUSPICIOUS_ACTIVITY',
  IP_BLOCKED = 'IP_BLOCKED',

  // Business Logic Errors
  BUSINESS_RULE_VIOLATION = 'BUSINESS_RULE_VIOLATION',
  WORKFLOW_STATE_INVALID = 'WORKFLOW_STATE_INVALID',
  OPERATION_NOT_ALLOWED = 'OPERATION_NOT_ALLOWED',
  RESOURCE_LOCKED = 'RESOURCE_LOCKED',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  QUOTA_EXCEEDED = 'QUOTA_EXCEEDED',

  // System Errors
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  CONFIGURATION_ERROR = 'CONFIGURATION_ERROR',
  FEATURE_NOT_IMPLEMENTED = 'FEATURE_NOT_IMPLEMENTED',
  MAINTENANCE_MODE = 'MAINTENANCE_MODE',

  // Pharmacy Errors
  PHARMACY_INVENTORY_NOT_FOUND = 'PHARMACY_INVENTORY_NOT_FOUND',
  PHARMACY_STOCK_INSUFFICIENT = 'PHARMACY_STOCK_INSUFFICIENT',
  PHARMACY_BATCH_EXPIRED = 'PHARMACY_BATCH_EXPIRED',
  PHARMACY_BATCH_NOT_FOUND = 'PHARMACY_BATCH_NOT_FOUND',
  PHARMACY_LOT_NUMBER_DUPLICATE = 'PHARMACY_LOT_NUMBER_DUPLICATE',
  PHARMACY_EXPIRY_DATE_INVALID = 'PHARMACY_EXPIRY_DATE_INVALID',
  PHARMACY_MANUFACTURE_DATE_INVALID = 'PHARMACY_MANUFACTURE_DATE_INVALID',
  PHARMACY_TRANSFER_NOT_FOUND = 'PHARMACY_TRANSFER_NOT_FOUND',
  PHARMACY_TRANSFER_INVALID_STATUS = 'PHARMACY_TRANSFER_INVALID_STATUS',
  PHARMACY_TRANSFER_CROSS_CLINIC_DENIED = 'PHARMACY_TRANSFER_CROSS_CLINIC_DENIED',
  PHARMACY_PURCHASE_ORDER_NOT_FOUND = 'PHARMACY_PURCHASE_ORDER_NOT_FOUND',
  PHARMACY_REORDER_RULE_NOT_FOUND = 'PHARMACY_REORDER_RULE_NOT_FOUND',
  PHARMACY_ALERT_NOT_FOUND = 'PHARMACY_ALERT_NOT_FOUND',

  // HIPAA & Compliance Errors
  HIPAA_VIOLATION = 'HIPAA_VIOLATION',
  AUDIT_LOG_FAILED = 'AUDIT_LOG_FAILED',
  DATA_RETENTION_VIOLATION = 'DATA_RETENTION_VIOLATION',
  CONSENT_EXPIRED = 'CONSENT_EXPIRED',
  PHI_ACCESS_UNAUTHORIZED = 'PHI_ACCESS_UNAUTHORIZED',
  AYURVEDA_INVALID_SAMPRAPTI_STAGE = 'AYURVEDA_INVALID_SAMPRAPTI_STAGE',
  AYURVEDA_INVALID_ASSESSMENT = 'AYURVEDA_INVALID_ASSESSMENT',
  AYURVEDA_PATIENT_REQUIRED = 'AYURVEDA_PATIENT_REQUIRED',
}
