/**
 * Jest configuration for the healthcare backend test suite.
 *
 * Three separate configs target unit, integration, and E2E suites so they
 * can be run independently or together.
 */
export default {
  // Unit tests — pure logic, mocked infrastructure
  unit: {
    displayName: 'unit',
    preset: 'ts-jest/presets/default-esm',
    testEnvironment: 'node',
    roots: ['<rootDir>/tests/unit'],
    testMatch: ['**/*.spec.ts'],
    transform: {
      '^.+\\.ts$': [
        'ts-jest',
        {
          useESM: true,
          tsconfig: '<rootDir>/tsconfig.test.json',
        },
      ],
    },
    moduleNameMapper: {
      '^@infrastructure/(.*)$': '<rootDir>/src/libs/infrastructure/$1',
      '^@services/(.*)$': '<rootDir>/src/services/$1',
      '^@dtos/(.*)$': '<rootDir>/src/libs/dtos/$1',
      '^@dtos$': '<rootDir>/src/libs/dtos',
      '^@core/(.*)$': '<rootDir>/src/libs/core/$1',
      '^@types/(.*)$': '<rootDir>/src/libs/core/types/$1',
      '^@logging/(.*)$': '<rootDir>/src/libs/infrastructure/logging/$1',
      '^@cache/(.*)$': '<rootDir>/src/libs/infrastructure/cache/$1',
      '^@events/(.*)$': '<rootDir>/src/libs/infrastructure/events/$1',
      '^@queue/(.*)$': '<rootDir>/src/libs/infrastructure/queue/$1',
      '^@security/(.*)$': '<rootDir>/src/libs/security/$1',
      '^@communication/(.*)$': '<rootDir>/src/libs/communication/$1',
      '^@config$': '<rootDir>/src/config',
      '^@config/(.*)$': '<rootDir>/src/libs/core/config/$1',
      '^@database/(.*)$': '<rootDir>/src/libs/infrastructure/database/$1',
      '^@utils/(.*)$': '<rootDir>/src/libs/utils/$1',
      '^@queues/(.*)$': '<rootDir>/src/libs/infrastructure/queue/$1',
    },
    collectCoverageFrom: [
      'src/services/**/*.ts',
      'src/libs/core/**/*.ts',
      '!src/**/*.dto.ts',
      '!src/**/*.module.ts',
      '!src/**/index.ts',
      '!src/**/*.spec.ts',
      '!src/**/*.e2e-spec.ts',
    ],
    coverageDirectory: '<rootDir>/coverage/unit',
    coverageProvider: 'v8',
    coverageThreshold: {
      global: {
        branches: 50,
        functions: 50,
        lines: 50,
        statements: 50,
      },
    },
    setupFilesAfterEnv: ['<rootDir>/tests/setup/jest-setup.ts'],
    transformIgnorePatterns: ['node_modules/(?!(uuid)/)'],
    extensionsToTreatAsEsm: ['.ts'],
    injectGlobals: true,
  },

  // Integration tests — real DB/cache, mocked external services
  integration: {
    displayName: 'integration',
    preset: 'ts-jest/presets/default-esm',
    testEnvironment: 'node',
    roots: ['<rootDir>/tests/integration'],
    testMatch: ['**/*.spec.ts'],
    transform: {
      '^.+\\.[tj]s$': [
        'ts-jest',
        {
          useESM: true,
          tsconfig: '<rootDir>/tsconfig.test.json',
        },
      ],
    },
    moduleNameMapper: {
      '^@infrastructure/(.*)$': '<rootDir>/src/libs/infrastructure/$1',
      '^@services/(.*)$': '<rootDir>/src/services/$1',
      '^@dtos/(.*)$': '<rootDir>/src/libs/dtos/$1',
      '^@dtos$': '<rootDir>/src/libs/dtos',
      '^@core/(.*)$': '<rootDir>/src/libs/core/$1',
      '^@types/(.*)$': '<rootDir>/src/libs/core/types/$1',
      '^@logging/(.*)$': '<rootDir>/src/libs/infrastructure/logging/$1',
      '^@cache/(.*)$': '<rootDir>/src/libs/infrastructure/cache/$1',
      '^@events/(.*)$': '<rootDir>/src/libs/infrastructure/events/$1',
      '^@queue/(.*)$': '<rootDir>/src/libs/infrastructure/queue/$1',
      '^@security/(.*)$': '<rootDir>/src/libs/security/$1',
      '^@communication/(.*)$': '<rootDir>/src/libs/communication/$1',
      '^@config$': '<rootDir>/src/config',
      '^@config/(.*)$': '<rootDir>/src/libs/core/config/$1',
      '^@database/(.*)$': '<rootDir>/src/libs/infrastructure/database/$1',
      '^@utils/(.*)$': '<rootDir>/src/libs/utils/$1',
      '^@queues/(.*)$': '<rootDir>/src/libs/infrastructure/queue/$1',
    },
    collectCoverageFrom: [
      'src/services/**/*.ts',
      'src/libs/infrastructure/**/*.ts',
      '!src/**/*.dto.ts',
      '!src/**/*.module.ts',
      '!src/**/index.ts',
      '!src/**/*.spec.ts',
      '!src/**/*.e2e-spec.ts',
    ],
    coverageDirectory: '<rootDir>/coverage/integration',
    coverageProvider: 'v8',
    setupFilesAfterEnv: ['<rootDir>/tests/setup/jest-setup.ts'],
    transformIgnorePatterns: ['node_modules/(?!(uuid)/)'],
    extensionsToTreatAsEsm: ['.ts'],
    injectGlobals: true,
    globalSetup: '<rootDir>/tests/setup/integration-setup.ts',
    globalTeardown: '<rootDir>/tests/setup/integration-teardown.ts',
  },

  // E2E tests — full NestJS app via supertest
  e2e: {
    displayName: 'e2e',
    preset: 'ts-jest/presets/default-esm',
    testEnvironment: 'node',
    roots: ['<rootDir>/tests/e2e'],
    testMatch: ['**/*.e2e-spec.ts'],
    transform: {
      '^.+\\.[tj]s$': [
        'ts-jest',
        {
          useESM: true,
          tsconfig: '<rootDir>/tsconfig.test.json',
        },
      ],
    },
    moduleNameMapper: {
      '^@infrastructure/(.*)$': '<rootDir>/src/libs/infrastructure/$1',
      '^@services/(.*)$': '<rootDir>/src/services/$1',
      '^@dtos/(.*)$': '<rootDir>/src/libs/dtos/$1',
      '^@dtos$': '<rootDir>/src/libs/dtos',
      '^@core/(.*)$': '<rootDir>/src/libs/core/$1',
      '^@types/(.*)$': '<rootDir>/src/libs/core/types/$1',
      '^@logging/(.*)$': '<rootDir>/src/libs/infrastructure/logging/$1',
      '^@cache/(.*)$': '<rootDir>/src/libs/infrastructure/cache/$1',
      '^@events/(.*)$': '<rootDir>/src/libs/infrastructure/events/$1',
      '^@queue/(.*)$': '<rootDir>/src/libs/infrastructure/queue/$1',
      '^@security/(.*)$': '<rootDir>/src/libs/security/$1',
      '^@communication/(.*)$': '<rootDir>/src/libs/communication/$1',
      '^@config$': '<rootDir>/src/config',
      '^@config/(.*)$': '<rootDir>/src/libs/core/config/$1',
      '^@database/(.*)$': '<rootDir>/src/libs/infrastructure/database/$1',
      '^@utils/(.*)$': '<rootDir>/src/libs/utils/$1',
      '^@queues/(.*)$': '<rootDir>/src/libs/infrastructure/queue/$1',
    },
    collectCoverageFrom: [
      'src/services/**/*.ts',
      'src/libs/**/*.ts',
      '!src/**/*.dto.ts',
      '!src/**/*.module.ts',
      '!src/**/index.ts',
      '!src/**/*.spec.ts',
      '!src/**/*.e2e-spec.ts',
    ],
    coverageDirectory: '<rootDir>/coverage/e2e',
    coverageProvider: 'v8',
    setupFilesAfterEnv: ['<rootDir>/tests/setup/jest-setup.ts'],
    transformIgnorePatterns: ['node_modules/(?!(uuid)/)'],
    extensionsToTreatAsEsm: ['.ts'],
    injectGlobals: true,
    globalSetup: '<rootDir>/tests/setup/e2e-setup.ts',
    globalTeardown: '<rootDir>/tests/setup/e2e-teardown.ts',
    testTimeout: 30000,
  },
};
