name: Deploy Healthcare Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write
  actions: read
  deployments: write

env:
  DOCKER_COMPOSE_VERSION: v2.20.2
  SERVER_HOST: api.ishswami.in
  SERVER_USER: ${{ secrets.SERVER_USER }}
  SERVER_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  DEPLOY_PATH: /var/www/healthcare/backend
  SERVER_IP: 82.208.20.16
  DOMAIN: api.ishswami.in
  FRONTEND_DOMAIN: ishswami.in
  SSL_EMAIL: aadeshbhujbal99@gmail.com
  NODE_ENV: production

jobs:
  pre-deployment-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check domain DNS and SSL
        run: |
          echo "Checking DNS for ${{ env.DOMAIN }}..."
          if ! nslookup ${{ env.DOMAIN }} > /dev/null 2>&1; then
            echo "Warning: Domain ${{ env.DOMAIN }} DNS resolution failed"
            echo "Please ensure domain is properly configured"
            exit 1
          fi

          echo "Checking SSL certificate expiry..."
          expiry=$(echo | openssl s_client -servername ${{ env.DOMAIN }} -connect ${{ env.DOMAIN }}:443 2>/dev/null | openssl x509 -noout -enddate 2>/dev/null | cut -d= -f2)
          if [ ! -z "$expiry" ]; then
            expiry_sec=$(date -d "$expiry" +%s)
            now_sec=$(date +%s)
            days_left=$(( ($expiry_sec - $now_sec) / 86400 ))
            if [ $days_left -lt 30 ]; then
              echo "Warning: SSL certificate will expire in $days_left days"
            fi
          fi

      - name: Check server connectivity and resources
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SERVER_SSH_KEY }}
          script: |
            echo "Checking system resources..."
            df -h
            free -m
            docker system df

            echo "Checking Docker status..."
            if ! docker info > /dev/null 2>&1; then
              echo "Docker is not running!"
              exit 1
            fi

            echo "Checking required ports..."
            for port in 8088 5432 6379 8082; do
              if netstat -tuln | grep -q ":$port "; then
                echo "Warning: Port $port is already in use"
                netstat -tuln | grep ":$port "
              fi
            done

            echo "Checking disk space..."
            DISK_USAGE=$(df -h / | awk 'NR==2 {print $5}' | sed 's/%//')
            if [ "$DISK_USAGE" -gt 85 ]; then
              echo "Warning: Disk usage is above 85%"
              df -h /
            fi

            echo "Checking SSL certificate paths..."
            for dir in "/etc/nginx/ssl" "/app/ssl"; do
              if [ ! -d "$dir" ]; then
                echo "Creating $dir directory..."
                sudo mkdir -p $dir
                sudo chmod 755 $dir
              fi
            done

  create-deployment:
    needs: [pre-deployment-check]
    runs-on: ubuntu-latest
    outputs:
      deployment_id: ${{ steps.create_deployment.outputs.deployment_id }}
    steps:
      - name: Create GitHub deployment
        id: create_deployment
        uses: actions/github-script@v6
        with:
          script: |
            const { data: deployment } = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha,
              environment: 'production',
              auto_merge: false,
              required_contexts: []
            });
            return deployment.id;

  deploy:
    needs: create-deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fix file permissions
        run: |
          chmod +x nginx/deploy-nginx.sh
          git add nginx/deploy-nginx.sh
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -m "chore: Make deploy-nginx.sh executable" || true

      - name: Create backup
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SERVER_SSH_KEY }}
          script: |
            cd ${{ env.DEPLOY_PATH }}
            timestamp=$(date +%Y%m%d_%H%M%S)
            mkdir -p backups/$timestamp
            if [ -d "current" ]; then
              cp -r current/* backups/$timestamp/
              echo $timestamp > backups/latest_backup
              
              # Backup SSL certificates
              if [ -d "current/nginx/ssl" ]; then
                cp -r current/nginx/ssl/* backups/$timestamp/ssl/
              fi
            fi

      - name: Prepare SSL files
        run: |
          # Create SSL directories
          mkdir -p ssl_temp
          # Copy and rename certificates
          cp nginx/ssl/ishswami.com.pem ssl_temp/api.ishswami.in.crt
          cp nginx/ssl/ishswami.com.key ssl_temp/api.ishswami.in.key

          # Verify SSL certificate
          echo "Verifying SSL certificate..."
          if ! openssl x509 -in ssl_temp/api.ishswami.in.crt -noout -text > /dev/null; then
            echo "Error: Invalid SSL certificate"
            exit 1
          fi

          # Check certificate matches private key
          echo "Checking certificate and key match..."
          cert_mod=$(openssl x509 -noout -modulus -in ssl_temp/api.ishswami.in.crt | openssl md5)
          key_mod=$(openssl rsa -noout -modulus -in ssl_temp/api.ishswami.in.key | openssl md5)
          if [ "$cert_mod" != "$key_mod" ]; then
            echo "Error: Certificate and private key do not match"
            exit 1
          fi

      - name: Copy SSL certificates
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SERVER_SSH_KEY }}
          source: "ssl_temp/*"
          target: "/tmp/ssl-temp"
          strip_components: 1

      - name: Copy deployment files
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SERVER_SSH_KEY }}
          source: "."
          target: "${{ env.DEPLOY_PATH }}/releases/${{ github.sha }}"
          strip_components: 0
          overwrite: true
          rm: false

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SERVER_SSH_KEY }}
          command_timeout: "30m"
          script: |
            set -e
            cd ${{ env.DEPLOY_PATH }}/releases/${{ github.sha }}

            # Setup SSL directories with proper permissions
            echo "Setting up SSL directories..."
            sudo mkdir -p /etc/nginx/ssl
            sudo mkdir -p /app/ssl
            sudo chown -R root:root /etc/nginx/ssl /app/ssl
            sudo chmod 755 /etc/nginx/ssl /app/ssl

            # Copy and secure SSL certificates
            if [ -d "/tmp/ssl-temp" ]; then
              echo "Copying SSL certificates..."
              sudo cp -f /tmp/ssl-temp/* /etc/nginx/ssl/
              sudo cp -f /tmp/ssl-temp/* /app/ssl/
              sudo chown root:root /etc/nginx/ssl/* /app/ssl/*
              sudo chmod 600 /etc/nginx/ssl/*.key /app/ssl/*.key
              sudo chmod 644 /etc/nginx/ssl/*.crt /app/ssl/*.crt
              rm -rf /tmp/ssl-temp
            else
              echo "No SSL files found in temp directory"
              exit 1
            fi

            # Verify SSL files and permissions
            echo "Verifying SSL files..."
            for file in /app/ssl/api.ishswami.in.key /app/ssl/api.ishswami.in.crt; do
              if [ ! -f "$file" ]; then
                echo "Error: SSL file $file not found"
                exit 1
              fi
              
              # Check permissions
              perms=$(stat -c "%a" $file)
              if [[ $file == *.key && $perms != "600" ]]; then
                echo "Error: Incorrect permissions on $file"
                exit 1
              elif [[ $file == *.crt && $perms != "644" ]]; then
                echo "Error: Incorrect permissions on $file"
                exit 1
              fi
            done

            # Start Docker services
            echo "Starting Docker services..."
            DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 docker compose -f docker-compose.prod.yml build --no-cache --parallel

            echo "Starting containers..."
            DEPLOY_SHA=$DEPLOY_SHA docker compose -f docker-compose.prod.yml up -d

            # Wait for services to be healthy
            echo "Waiting for services to be healthy..."
            attempt=1
            max_attempts=30
            while [ $attempt -le $max_attempts ]; do
              if curl -k -s https://localhost:8088/health | grep -q "ok"; then
                echo "API service is healthy"
                break
              fi
              echo "Attempt $attempt/$max_attempts: Waiting for API service..."
              sleep 10
              attempt=$((attempt + 1))
            done

            if [ $attempt -gt $max_attempts ]; then
              echo "Error: API service failed to become healthy"
              docker compose -f docker-compose.prod.yml logs api
              exit 1
            fi

            # Verify SSL configuration
            echo "Verifying SSL configuration..."
            if ! curl -k -s -o /dev/null -w "%{http_code}" https://localhost:8088/health | grep -q "200"; then
              echo "Error: SSL configuration test failed"
              exit 1
            fi

            echo "Deployment completed successfully"

  rollback:
    if: failure() && needs.deploy.result == 'failure'
    needs: [deploy, create-deployment]
    runs-on: ubuntu-latest
    steps:
      - name: Rollback deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SERVER_SSH_KEY }}
          script: |
            set -e
            cd ${{ env.DEPLOY_PATH }}

            if [ -f backups/latest_backup ]; then
              timestamp=$(cat backups/latest_backup)
              echo "Rolling back to backup from $timestamp"

              # Stop current services
              cd current
              docker compose -f docker-compose.prod.yml down --remove-orphans || true

              # Restore from backup
              cd ${{ env.DEPLOY_PATH }}
              rm -rf current
              cp -r backups/$timestamp current/

              # Start services from backup
              cd current
              docker compose -f docker-compose.prod.yml up -d

              echo "Rollback completed successfully"
            else
              echo "No backup found for rollback"
              exit 1
            fi

      - name: Update deployment status
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const status = '${{ job.status }}' === 'success' ? 'success' : 'failure';
            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: ${{ needs.create-deployment.outputs.deployment_id }},
              state: status,
              environment: 'production'
            });
