name: Deploy Healthcare Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write
  actions: read
  deployments: write

env:
  DOCKER_COMPOSE_VERSION: v2.20.2
  SERVER_HOST: api.ishswami.in
  SERVER_USER: ${{ secrets.SERVER_USER }}
  SERVER_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  DEPLOY_PATH: /var/www/healthcare/backend
  SERVER_IP: 82.208.20.16
  DOMAIN: api.ishswami.in
  FRONTEND_DOMAIN: ishswami.in
  SSL_EMAIL: aadeshbhujbal99@gmail.com
  NODE_ENV: production

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --passWithNoTests

  pre-deployment-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check domain DNS
        run: |
          echo "Checking DNS for ${{ env.DOMAIN }}..."
          if ! nslookup ${{ env.DOMAIN }} > /dev/null 2>&1; then
            echo "Warning: Domain ${{ env.DOMAIN }} DNS resolution failed"
            echo "Please ensure domain is properly configured"
          fi

      - name: Check server connectivity and resources
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SERVER_SSH_KEY }}
          script: |
            echo "Checking system resources..."
            df -h
            free -m
            docker system df

            echo "Checking Docker status..."
            if ! docker info > /dev/null 2>&1; then
              echo "Docker is not running!"
              exit 1
            fi

            echo "Checking required ports..."
            for port in 8088 5432 6379 8082; do
              if netstat -tuln | grep -q ":$port "; then
                echo "Warning: Port $port is already in use"
                netstat -tuln | grep ":$port "
              fi
            done

            echo "Checking disk space..."
            DISK_USAGE=$(df -h / | awk 'NR==2 {print $5}' | sed 's/%//')
            if [ "$DISK_USAGE" -gt 85 ]; then
              echo "Warning: Disk usage is above 85%"
              df -h /
            fi

  create-deployment:
    needs: [test, pre-deployment-check]
    runs-on: ubuntu-latest
    outputs:
      deployment_id: ${{ steps.create_deployment.outputs.deployment_id }}
    steps:
      - name: Create GitHub deployment
        id: create_deployment
        uses: actions/github-script@v6
        with:
          script: |
            const { data: deployment } = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha,
              environment: 'production',
              auto_merge: false,
              required_contexts: []
            });
            return deployment.id;

  deploy:
    needs: create-deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create backup
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SERVER_SSH_KEY }}
          script: |
            cd ${{ env.DEPLOY_PATH }}
            timestamp=$(date +%Y%m%d_%H%M%S)
            mkdir -p backups/$timestamp
            if [ -d "current" ]; then
              cp -r current/* backups/$timestamp/
              echo $timestamp > backups/latest_backup
            fi

      - name: Setup SSL certificates
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SERVER_SSH_KEY }}
          script: |
            cd ${{ env.DEPLOY_PATH }}
            ./nginx/deploy-nginx.sh

      - name: Copy deployment files
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SERVER_SSH_KEY }}
          source: ".,!node_modules,!dist,!.git"
          target: "${{ env.DEPLOY_PATH }}/releases/${{ github.sha }}"
          strip_components: 0
          overwrite: true

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SERVER_SSH_KEY }}
          envs: NODE_ENV
          script: |
            set -e
            cd ${{ env.DEPLOY_PATH }}

            # Create production environment file
            cat > releases/${{ github.sha }}/.env.production << EOL
            NODE_ENV=${NODE_ENV}
            CORS_ORIGIN=https://ishswami.in
            FRONTEND_URL=https://ishswami.in
            EOL

            echo "Setting up Nginx configuration..."
            if [ -d "releases/${{ github.sha }}/nginx/conf.d" ]; then
              sudo cp -f releases/${{ github.sha }}/nginx/conf.d/*.conf /etc/nginx/conf.d/
              sudo nginx -t && sudo systemctl reload nginx
            fi

            echo "Stopping existing services..."
            cd releases/${{ github.sha }}
            docker compose -f docker-compose.prod.yml down --remove-orphans || true

            echo "Building and starting services..."
            docker compose -f docker-compose.prod.yml up --build -d

            echo "Waiting for services to start up (initial delay: 60s)..."
            sleep 60

            timeout=360
            start_time=$(date +%s)

            while true; do
              current_time=$(date +%s)
              elapsed=$((current_time - start_time))
              
              if [ $elapsed -gt $timeout ]; then
                echo "Timeout waiting for services to be healthy"
                docker compose -f docker-compose.prod.yml logs
                exit 1
              fi
              
              api_healthy=$(docker ps --filter "name=healthcarebackend-api-1" --format "{{.Status}}" | grep -q "healthy" && echo "yes" || echo "no")
              postgres_healthy=$(docker ps --filter "name=postgres" --format "{{.Status}}" | grep -q "healthy" && echo "yes" || echo "no")
              redis_healthy=$(docker ps --filter "name=healthcarebackend-redis-1" --format "{{.Status}}" | grep -q "healthy" && echo "yes" || echo "no")
              
              echo "API: $api_healthy, PostgreSQL: $postgres_healthy, Redis: $redis_healthy"
              
              if [ "$api_healthy" = "yes" ] && [ "$postgres_healthy" = "yes" ] && [ "$redis_healthy" = "yes" ]; then
                echo "All services are healthy!"
                break
              fi
              
              sleep 20
            done

            # Verify API is responding
            echo "Verifying API health..."
            if curl -f https://${{ env.DOMAIN }}/health; then
              echo "API is responding correctly"
            else
              echo "API health check failed"
              exit 1
            fi

            # Update current symlink
            cd ${{ env.DEPLOY_PATH }}
            ln -sfn releases/${{ github.sha }} current

            # Keep only last 5 releases
            cd releases
            ls -t | tail -n +6 | xargs rm -rf

            echo "Deployment successful!"

  rollback:
    if: failure() && needs.deploy.result == 'failure'
    needs: [deploy, create-deployment]
    runs-on: ubuntu-latest
    steps:
      - name: Rollback deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SERVER_SSH_KEY }}
          script: |
            set -e
            cd ${{ env.DEPLOY_PATH }}

            if [ -f backups/latest_backup ]; then
              timestamp=$(cat backups/latest_backup)
              echo "Rolling back to backup from $timestamp"

              # Stop current services
              cd current
              docker compose -f docker-compose.prod.yml down --remove-orphans || true

              # Restore from backup
              cd ${{ env.DEPLOY_PATH }}
              rm -rf current
              cp -r backups/$timestamp current/

              # Start services from backup
              cd current
              docker compose -f docker-compose.prod.yml up -d

              echo "Rollback completed successfully"
            else
              echo "No backup found for rollback"
              exit 1
            fi

      - name: Update deployment status
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const status = '${{ job.status }}' === 'success' ? 'success' : 'failure';
            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: ${{ needs.create-deployment.outputs.deployment_id }},
              state: status,
              environment: 'production'
            });
